---
title: "intro_to_R_session3_worked_solution"
author: ""
date: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r source}
library(tidyverse)
source("./R/Analysis.R")

```

## Plot of total FTE over time

```{r plot}

# Plot
plt <-ggplot(data_all, aes(x = as.Date(date), 
                            y = total_fte, 
                            group = benefit, 
                            colour = benefit)) +
  geom_line() +
  xlab("Date") +
  ylab("FTE") +
  scale_x_date(breaks = "1 year")
  
plt

```

## Table of median annual FTE

```{r table, results = "asis"}
data_all_median <- data_all %>%
  #you can call functions to create variables in the group_by argument
  group_by(Year = year(date), benefit) %>%
  summarise(median_fte = round(median(total_fte), 1)) %>%
  pivot_wider(names_from = "benefit", values_from = "median_fte") %>%
  #you can draw on functions from libraries that you don't want to load using :: . 
  #knitr::kable is a pretty html table formatting library
  #see https://rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf for other table formatting suggestions. Note, you need results = "asis" for the kable html output, also DT::datatable
  knitr::kable(caption = "Median Annual FTE by Benefit")
data_all_median


```
